name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    uses: ixoworld/ixo-github-actions/.github/workflows/node-monorepo-ci-build.yml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write
      pull-requests: write
    with:
      pnpm-version: '10.0.0'
      node-version: '22.17.0'
